# Language flags.
language: elixir

# OS matrix.
os:
  - linux

# Version matrix (language).
elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2

# Version matrix (OTP).
otp_release:
  - 23.0
  - 22.3
  - 21.3
  - 20.3
  - 19.3
  - 18.3

# Matrix modifications.
matrix:
  # Additional builds.
  include:
    - elixir: 1.10
      otp_release: 23.0
      script:
        - MIX_ENV=cover mix coveralls.travis --trace
    - elixir: 1.10
      otp_release: 23.0
      script:
        - mix credo --all --format=oneline
    - elixir: 1.10
      otp_release: 23.0
      script:
        - mix bench

  # Incompatible pairs.
  exclude:
    - elixir: 1.10
      otp_release: 20.3
    - elixir: 1.10
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 18.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 18.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3
    - elixir: 1.7
      otp_release: 18.3
    - elixir: 1.6
      otp_release: 23.0
    - elixir: 1.6
      otp_release: 22.3
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 23.0
    - elixir: 1.5
      otp_release: 22.3
    - elixir: 1.5
      otp_release: 21.3
    - elixir: 1.5
      otp_release: 18.3
    - elixir: 1.4
      otp_release: 23.0
    - elixir: 1.4
      otp_release: 22.3
    - elixir: 1.4
      otp_release: 21.3
    - elixir: 1.4
      otp_release: 18.3
    - elixir: 1.3
      otp_release: 23.0
    - elixir: 1.3
      otp_release: 22.3
    - elixir: 1.3
      otp_release: 21.3
    - elixir: 1.3
      otp_release: 20.3
    - elixir: 1.3
      otp_release: 18.3
    - elixir: 1.2
      otp_release: 23.0
    - elixir: 1.2
      otp_release: 22.3
    - elixir: 1.2
      otp_release: 21.3
    - elixir: 1.2
      otp_release: 20.3
    - elixir: 1.2
      otp_release: 18.3
  allow_failures:
    - elixir: 1.10
      otp_release: 23.0
      script:
        - mix bench
branches:
  only:
    - master

# Environment setup.
before_install:
  - epmd -daemon
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

# Test commands.
script:
  - mix test --trace
