language: elixir
elixir:
  - 1.4.2
  - 1.3.4
  - 1.2.6
otp_release:
  - 19.2
  - 18.3
before_install:
  - mix local.rebar --force
script:
  - mix credo --all --format=oneline
  - mix coveralls.travis --trace
  - mix bench
branches:
  only:
    - master
env:
  - MIX_ENV=test
