language: elixir
elixir:
  - 1.6.4
  - 1.5.3
  - 1.4.5
  - 1.3.4
  - 1.2.6
otp_release:
  - 20.3
  - 19.3
  - 18.3
matrix:
  exclude:
  - elixir: 1.6.4
    otp_release: 18.3
  - elixir: 1.3.4
    otp_release: 20.3
  - elixir: 1.2.6
    otp_release: 20.3
branches:
  only:
  - master
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix credo --all --format=oneline
  - mix coveralls.travis --trace
