language: elixir
elixir:
  - 1.4.5
  - 1.3.4
  - 1.2.6
otp_release:
  - 20.0
  - 19.3
  - 18.3
env:
  - MIX_ENV=test
matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0
  - elixir: 1.2.6
    otp_release: 20.0
before_install:
  - mix local.rebar --force
script:
  - mix credo --all --format=oneline
  - mix coveralls.travis --trace
  - mix bench
branches:
  only:
    - master
