version: '{branch}-{build}'

skip_commits:
  message: /\[skip ci\]/

environment:
  elixir_version: 1.6.0

branches:
  only:
    - master

cache:
  - '%APPDATA%\Local\Temp -> appveyor.yml'

install:
  - cinst elixir --version %elixir_version%
  - refreshenv

build_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test_script:
  - mix credo --all --format=oneline
  - MIX_ENV=cover mix test --trace
